version: 1
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: Europe/Athens
    open-pull-requests-limit: 10
    reviewers:
      - TommyDunn
    labels:
      - dependencies
    versioning-strategy: increase
